/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.natlus.percobaan4;

import javax.swing.table.DefaultTableModel;

/**
 * @author kaito
 */
public class TampilGui1841720019Sultan extends javax.swing.JFrame {

    /**
     * Creates new form TampilGui1841720019Sultan
     */
    public TampilGui1841720019Sultan() {
        initComponents();
        lihaDataMahasiswaSultan();
    }

    public final void lihaDataMahasiswaSultan() {
        String[] namaKolom = {"NIM", "Nama Mahasiswa", "Alamat"};
        Object[][] objekMahasiswa = new Object[dataMahasiswa.getDataSultan().size()][3];
        int i = 0;
        for (Mahasiswa1841720019Sultan mhs : dataMahasiswa.getDataSultan()) {
            String[] arrayMahasiswa = {mhs.getmNimSultan(), mhs.getmNamaSultan(), mhs.getmAlamatSultan()};
            objekMahasiswa[i] = arrayMahasiswa;
            i++;
        }
        tableMahasiswa = new DefaultTableModel(objekMahasiswa, namaKolom);
        mTable.setModel(tableMahasiswa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanel = new javax.swing.JPanel();
        mLblNim = new javax.swing.JLabel();
        mLblNama = new javax.swing.JLabel();
        mLblAlamat = new javax.swing.JLabel();
        mTxtFieldAlamat = new javax.swing.JTextField();
        mTxtFieldNama = new javax.swing.JTextField();
        mTxtFieldNim = new javax.swing.JTextField();
        mBtnSimpan = new javax.swing.JButton();
        mScrlPanel = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mLblNim.setText("NIM");

        mLblNama.setText("Nama");

        mLblAlamat.setText("Alamat");

        mBtnSimpan.setText("Simpan");
        mBtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBtnSimpanActionPerformed(evt);
            }
        });

        mTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "NIM", "Nama Mahasiswa", "Alamat"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        mScrlPanel.setViewportView(mTable);

        javax.swing.GroupLayout mPanelLayout = new javax.swing.GroupLayout(mPanel);
        mPanel.setLayout(mPanelLayout);
        mPanelLayout.setHorizontalGroup(
                mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mScrlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                        .addGroup(mPanelLayout.createSequentialGroup()
                                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(mLblAlamat)
                                                        .addComponent(mLblNim)
                                                        .addComponent(mLblNama))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(mBtnSimpan)
                                                        .addComponent(mTxtFieldAlamat)
                                                        .addComponent(mTxtFieldNama)
                                                        .addComponent(mTxtFieldNim, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        mPanelLayout.setVerticalGroup(
                mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mLblNim)
                                        .addComponent(mTxtFieldNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mLblNama)
                                        .addComponent(mTxtFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mLblAlamat)
                                        .addComponent(mTxtFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(mBtnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(mScrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mBtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnSimpanActionPerformed
        dataMahasiswa.isiDataSultan(mTxtFieldNim.getText(), mTxtFieldNama.getText(), mTxtFieldAlamat.getText());
        lihaDataMahasiswaSultan();
    }//GEN-LAST:event_mBtnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGui1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGui1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGui1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGui1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGui1841720019Sultan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mBtnSimpan;
    private javax.swing.JLabel mLblAlamat;
    private javax.swing.JLabel mLblNama;
    private javax.swing.JLabel mLblNim;
    private javax.swing.JPanel mPanel;
    private javax.swing.JScrollPane mScrlPanel;
    private javax.swing.JTable mTable;
    private javax.swing.JTextField mTxtFieldAlamat;
    private javax.swing.JTextField mTxtFieldNama;
    private javax.swing.JTextField mTxtFieldNim;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel tableMahasiswa;
    private InputData1841720019Sultan dataMahasiswa = new InputData1841720019Sultan();
}
